Parameters:
  GitHubRepo:
    Type: String
    Description: URL for GitHub repo i.e. https://github.com/username/repository
  GitHubToken:
    Type: String
    Description: Access Github Token

Resources:
  CodeBuildCredentials:
    Type: AWS::CodeBuild::SourceCredential
    Properties:
      ServerType: GITHUB
      AuthType: PERSONAL_ACCESS_TOKEN
      Token: !Ref GitHubToken
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
            - Effect: Allow
              Principal:
                  Service:
                    - codebuild.amazonaws.com
              Action:
                - sts:AssumeRole
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Triggers:
        BuildType: BUILD
        Webhook: False
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: ARM_CONTAINER
        ComputeType: BUILD_GENERAL1_LARGE 
        Image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
        #EnvironmentVariables:
        #  - Name: MY_ENV_VAR
        #    Value: something
        #    Type: PLAINTEXT
      Source:
        BuildSpec: buildspec.yaml
        Type: GITHUB
        Location: !Ref GitHubRepo
      TimeoutInMinutes: 15
  CodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/codebuild/${CodeBuild}"
      RetentionInDays: 7

Outputs:
  ProjectName:
    Value: !Ref CodeBuild
    Description: CodeBuild project name
